### ISSUE TITLE
libmetrics/linux/metrics.c and network counter bit width

### ISSUE THREAD

**Issue by johntconklin** [ganglia/monitor-core#140]
libmetrics/linux/metrics.c assumes the presence of 64 bit network counters in /proc/dev/net if configure detects stroull() (thus defining HAVE_STRTOULL).

This causes issues on iX86 (and presumably other 32 bit) Linux systems, as it has 32 bit network counters. When the 32 bit counters overflow, a huge bias is added, resulting in erratic and erroneous network traffic spikes.

For my personal ganglia deployment, I changed the preprocessor conditional that selected the network statistic type to use **i386** instead of HAVE_STRTOULL.  This may not be the best solution for integration into the master sources, as it doesn't address the fact that there are other 32 bit Linux architectures.  There's also the possibility that a 32 bit gmond could be run on a 64 bit system of the same architectural family (although I'm not sure this is worth consideration, as there may be issues (other than network counter width) that preclude this from working).

**Comment by bkurtz** [comment]
I was lucky and caught this very shortly after I first installed ganglia on a 32-bit host, so things hadn't been averaged out (in time) too much yet.  I cleaned up my RRD files by doing (approximately)

    cd /var/lib/ganglia/rrds/CLUSTER/HOST
    rrdtool dump bytes_in.rrd > /tmp/bytes_in.xml
    sed -E -e 's/e\+1[567]/e+01/' -i /tmp/bytes_in.xml
    rrdtool restore -f /tmp/bytes_in.xml bytes_in.rrd

(basically, find any network levels greater than 10^15 and drop them down so the exponent is 1 instead of 15, 16, or 17, i.e. basically set to zero).  It won't be 100% accurate, but it's an easy way to do the change, and 100% accuracy doesn't really matter so long as you don't have those 10^17s getting averaged in to your data and messing up the scaling on the graphs.
