### ISSUE TITLE
If you load two ganglia modules with the same name, gmond uses up 100% of available resources

### ISSUE THREAD

**Issue by ghost** [ganglia/monitor-core#44]
The following configuration in Ganglia (3.4) will give you a really bad day, and cause Ganglia to sit in a loop where it consumes all available memory:
```
modules {
  module {
    name = "cpu_module"
    path = "/usr/lib/ganglia/modcpu.so"
  }
  module {
    name = "cpu_module"
    path = "/usr/lib64/ganglia/modcpu.so"
  }
}
```

**Comment by hawson** [comment]
Confirmed.  That's pretty awful.  However, it only happens if both the `name` and `path` are simultaneously duplicated.  So if two modules have the same "name", but different "path" attributes, there's no crash.  Likewise, different names, pointing to the same .so file also doesn't cause the same problem.
